[package]
name = "pg_lease"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
rand = "0.9.1"
sqlx = { version = "0.8.6", features = [
  "postgres",
  "chrono",
  "runtime-tokio-rustls",
] }
tokio = { version = "1.45.1", features = ["full"] }
